### ISSUE TITLE
Input values are not validated before patch operation

### ISSUE THREAD

**Issue by shankar-janagoud** [HewlettPackard/python-ilorest-library-EOL#11]
Body is not validated before patch operation

For example: BIOS property patching
Actual: When user is trying to patching the property or value which is improper, the API doesn’t through any exception.

Expected: API should prompt proper exception.

Before patch operation validation of the body(property and value) is necessary and the all supported properties/values/field can be found http://h22208.www2.hpe.com/eginfolib/servers/docs/HPRestfultool/iLo4/data_model_reference.html

settings = { "PowerProfile": "MaxPerf"}
response = bios_rest_obj.patch(path = uri,
                                          body = settings,
                                          optionalpassword = None)

For property PowerProfile:
String containing one of the following supported values:
"BalancedPowerPerf" Balanced Power and Performance
"MinPower"  Minimum Power Usage
"MaxPerf"   Maximum Performance
"Custom"    Custom

If user tries to patch any value other than the supported values then exception should be thrown.
Even if user tries with Property name being wrong then also it shouldn’t be supported(Example: settings = { "Invalid_Property_Name": "Invalid_Value"}

**Comment by LumbaJack** [comment]
The examples are an implementation of using V1 as a pass through to iLO. The functionality you are asking for is derived from the RMC class. We will soon publish HPREST which is our implementation of the RMC class. This will have the schema validations and caching systems.

**Comment by LumbaJack** [comment]
@shankar-janagoud  we have open sourced our utility. There you will find the proper usage of the RMC class with all the data validation. https://github.com/HewlettPackard/python-redfish-utility
