### ISSUE TITLE
RestObject - Not imported

### ISSUE THREAD

**Issue by seannienaber** [HewlettPackard/python-ilorest-library-EOL#12]
Hi,

I've followed the installation as documented and it completed without errors.

quickstart.py works without issue, however all other scripts fail as follows:

`File "ilo_change.py", line 17, in <module>
    from restobject import RestObject
ImportError: No module named restobject
`

I'm not sure how to install that module?

**Comment by daverickdunn** [comment]
Hi @seannienaber, they changed the examples layout recently, a few commits ago the RestObject class was separated from the examples but not incorporated in the main library. It's currently listed along with the other example files, see the last file here: https://github.com/HewlettPackard/python-ilorest-library/tree/master/examples/Rest

/Rich

**Comment by seannienaber** [comment]
Brilliant, thanks for the super fast response Rich.

**Comment by daverickdunn** [comment]
No worries - it caught me out for a few minutes as well...
