### ISSUE TITLE
Does this work for HP Insight CMU (Moonshot)?

### ISSUE THREAD

**Issue by rdeusser** [HewlettPackard/python-ilorest-library-EOL#13]
I suspect that it wouldn't, but I figured I'd ask anyway.

**Comment by LumbaJack** [comment]
They wont work without modification. They are based on the resource directory and the moonshot servers don't have it. What exactly are you trying to do? I may be able to help you modify them to work for you.

**Comment by rdeusser** [comment]
@LumbaJack I basically want to create a Python CLI to the CMU so I don't have to use the web GUI. I prefer working in a CLI environment. I need to be able to create an autoinstall image group and run a kickstart on all of the cartridges in a Moonshot chassis.

**Comment by LumbaJack** [comment]
Have you used HPREST before? This may be what you are looking for as it is built on top of this library. http://www8.hp.com/us/en/products/server-software/product-detail.html?oid=7630408

PS> it is going open source very soon.

**Comment by rdeusser** [comment]
I haven't used it before. I'll see what that can do for me. Thanks!

**Comment by rdeusser** [comment]
@LumbaJack Is it written in Python? I would be nice to be able to call this from Python directly.

**Comment by LumbaJack** [comment]
Yes it is written in python and will be modular so that you can build your own version of the utility.

**Comment by brookshire** [comment]
@iamthemuffinman You can drive CMU using the CLI utilities in /opt/cmu/bin, and /opt/cmu/tools.  The Moonshot Provisioning Manager sits on top of CMU and does just that.  You can download MPM and look at the source in /opt/hp/moonshot/tinkerbell/prov_mgr/cmu.py--that is the wrapper around the CMU CLI tools.

**Comment by rdeusser** [comment]
@brookshire Awesome! Do you know where I can get MPM at?

**Comment by brookshire** [comment]
It is distributed as a VM image at https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=HPMPM1

**Comment by brookshire** [comment]
If you don't have VM player, I can find the RPM and upload it to an FTP site.

**Comment by LumbaJack** [comment]
@iamthemuffinman did this resolve your issue?

**Comment by rdeusser** [comment]
@LumbaJack Ah, yes sorry I forgot to close this. Thank you!
