### ISSUE TITLE
KeyError: 'Type'

### ISSUE THREAD

**Issue by nivazri** [HewlettPackard/python-ilorest-library-EOL#16]
Is the examples support hp Gen8 servers?
i run ex20_get_ilo_nic, ex09_find_ilo_mac_address

in line 103 _restobject.py throw KeyError: 'Type'
(rest examples)

**Comment by LumbaJack** [comment]
The examples primarily work on Gen 9 servers. A few of them will work for Gen 8 since iLO has limited supported for features. The error you are seeing is because that type doesn't exist in Gen 8.
