### ISSUE TITLE
1.6.0 : ImportError: No module named _redfishobject 

### ISSUE THREAD

**Issue by fwfly** [HewlettPackard/python-ilorest-library-EOL#17]
Hi,

I got an exception with 1.6.0 sdk.
There is only "redfish" dir in "site-packages" dir
Which one should I use ? redfish or  RedfishObject ?

pip list result : 
   python-ilorest-library (1.6.0)

python -c "import RedfishObject" :    
   Traceback (most recent call last):
        File "<string>", line 1, in <module>
    ImportError: No module named RedfishObject

Thanks

**Comment by Yergidy** [comment]
Hi, 
If you would like to use the "RedfishObject" class import it from _redfishobject.py in the Redfish folder of the examples. If you would like to directly use the library, see "quickstart_redfish.py" in the examples folder.

**Comment by fwfly** [comment]
Hi,
I will follow  "quickstart_redfish.py".
Thanks for response.
