### ISSUE TITLE
Issue after putting HPrest_chif.so file

### ISSUE THREAD

**Issue by vinantip** [HewlettPackard/python-ilorest-library-EOL#19]
**"This issue is coming after version 1.4.0"
It working fine till 1.4.0.

Please fix this as this comes for inband communication** 

AttributeError: /root/python-ilorest-library/examples/Rest/hprest_chif.so: undefined symbol: size_of_responseHeaderBlob
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 877, in emit
    self.flush()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 837, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file v1.py, line 959

**Comment by LumbaJack** [comment]
@vinantip I have updated the download links. Please retry with latest version.

**Comment by vinantip** [comment]
thank you for the quick update on the changed links. 
Now though the value is coming as fine still there is one error which comes attached to it
EXAMPLE 30: Report PowerMetrics Average Watts
         AverageConsumedWatts = 32 watts over a 20 minute moving average
**Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/__init__.py", line 877, in emit
    self.flush()
  File "/usr/local/lib/python2.7/logging/__init__.py", line 837, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file v1.py, line 959**

**Comment by LumbaJack** [comment]
@vinantip I tried to reproduce but I wasn't able to reproduce this issue. Can you share some details of your current setup so I can try to reproduce this here.

**Comment by LumbaJack** [comment]
Closing since the issue is not able to be reproduced.
