### ISSUE TITLE
Disable "Use DHCPv4 Supplied Time Settings" in SNTP setting

### ISSUE THREAD

**Issue by herrryan** [HewlettPackard/python-ilorest-library-EOL#20]
The default setting for ntp is using dhcp v4 and v6 supplied time settings, is there a API to disable these two options so that we could programically set our own ntp servers.

**Comment by LumbaJack** [comment]
@herrryan There is a setting located at: /rest/v1/Managers/1/EthernetInterfaces. There you will find the propery for your needs under Items/Oem/Hp/DHCPv4/UseNTPServers or Items/Oem/Hp/DHCPv6/UseNTPServers. For more information please visit: https://hewlettpackard.github.io/ilo4-rest-api-docs/#ethernetinterface and look for the property UseNTPServers.

**Comment by LumbaJack** [comment]
Closing issue please reopen if the answer didn't provide you a solution.
