### ISSUE TITLE
pip install python-ilorest-library doesn't work.

### ISSUE THREAD

**Issue by kckaiwei** [HewlettPackard/python-ilorest-library-EOL#4]
pip install isn't working, giving this error.

>   Could not fetch URL https://pypi.python.org/simple/python-ilorest-library/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
>   Could not find a version that satisfies the requirement python-ilorest-library (from versions: )
> No matching distribution found for python-ilorest-library

Looked into it, but can't find the project.
- Searching for python-ilorest-library in the directory of: https://pypi.python.org/simple/
- Gives no results. Can't find the project there manually either.

**Comment by LumbaJack** [comment]
Thanks for pointing that out issue should now be fixed.
