### ISSUE TITLE
Inband location links are broken

### ISSUE THREAD

**Issue by joehandzik** [HewlettPackard/python-ilorest-library-EOL#6]
Both pages yield the following error:

Could not open page

The service or information you requested is not available at this time. 
Please try again later.

(Error: system-websrv_unavail)

**Comment by LumbaJack** [comment]
Thanks for pointing that out. Links should now be up.

**Comment by joehandzik** [comment]
No worries, thanks for the fix!

Joe

On May 23, 2016, at 11:49 AM, Jack Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for pointing that out. Links should now be up.

##

**Comment by JohanElmis** [comment]
Greetings! 

I thought you  might be interested in that list of books I made especially  for  you, just take a look http://frytrethafy.nationsbadcredit.com/e4hmsmdx

See you soon, johan

**Comment by JohanElmis** [comment]
Hello, 
We've got  some  great news for you! Just  take a  look  http://quecreslecu.amieartist.com/e4ybjwhv

Yours sincerely, johan
