### ISSUE TITLE
IML Log severity levels

### ISSUE THREAD

**Issue by daverickdunn** [HewlettPackard/python-ilorest-library-EOL#8]
Hi guys,

I'm trying to parse IML warnings and find it a little strange that serious errors such as the ones below all have a severity level of 'OK'. These errors are due to a CPU needing re-seating - can't get much more severe than that.

Following: [Gen9 Troubleshooting Guide](http://h20564.www2.hpe.com/hpsc/doc/public/display?docId=c04443553), there appears to be no information on the 'Class' and 'Code' attributes either. Save hard coding strings to match all the pertinent errors in that document, I'm not sure how I can classify critical errors easily, I imagine that's what the 'Severity' attribute is supposed to do.

Am I correct in thinking this is an issue, or am I misinterpreting what the severity attribute is actually supposed to indicate?

*The below is output from 'ex22_dump_iml.py'

OK: Class 5 / Code 3:   Uncorrectable Machine Check Exception (Board 0, Processor 1, APIC ID 0x00000018, Bank 0x00000013, Status 0xFE200000'000C110A, Address 0x00000040'53500500, Misc 0xE8FCF016'1F002086)
OK: Class 20 / Code 5:  Unrecoverable System Error (NMI) has occurred.  System Firmware will log additional details in a separate IML entry if possible
OK: Class 8 / Code 2:   Uncorrectable PCI Express Error (Embedded device, Bus 0, Device 2, Function 0, Error status 0x00000024)
OK: Class 5 / Code 3:   Uncorrectable Machine Check Exception (Board 0, Processor 1, APIC ID 0x00000000, Bank 0x00000004, Status 0xF2000000'00400407, Address 0x00000000'00000000, Misc 0x00000000'00000000)
OK: Class 8 / Code 2:   Uncorrectable PCI Express Error (Embedded device, Bus 0, Device 2, Function 0, Error status 0x0000002C)
OK: Class 5 / Code 3:   Uncorrectable Machine Check Exception (Board 0, Processor 1, APIC ID 0x00000000, Bank 0x00000003, Status 0xB2000000'00800400, Address 0x00000000'71CBC3C0, Misc 0x00000000'00000085)
OK: Class 5 / Code 3:   Uncorrectable Machine Check Exception (Board 0, Processor 1, APIC ID 0x00000010, Bank 0x00000003, Status 0xB2000000'00800400, Address 0x00000000'7FA0EB40, Misc 0x00000000'00700085)

Thanks.

**Comment by daverickdunn** [comment]
Okay, I think I see the missing link. These logs have been edited: someone must have set them to 'Repaired' via the Web GUI, and this is presumably reflected as 'OK' in the system. Assuming this is in fact correct, then this is a non-issue.

Edit: I'm looking through several documents and cannot find any reference to the web-term 'Repaired' being stored as 'OK' in the actual logs. Perhaps adding a comment with all possible severity strings would go a long way in this example, as it's impossible to tell what the actual strings are without having an example. Thanks.

**Comment by JohanElmis** [comment]
Dear! 

Just take a look at that cool stuff I  just have found, it's so  fantastic! Here  it is http://spuzenije.newsmyrnabeachphotographer.com/e4udznl

johan
